### ISSUE TITLE
add open file button after download complete

### ISSUE THREAD

**Issue by raulpy271** [amantiwari1/youtube-GUI#10]
Did you want that the app to also be a video player?

**Comment by amantiwari1** [comment]
No,. This file will be open by vlc, windows media player etc
Also show in folder where video has been saved

**Comment by amantiwari1** [comment]
I can work on it. No issue!

**Comment by amantiwari1** [comment]
In models
we can create 2 columns called `isDownloadComplele` (boolean )  and `filesave`  (string) in video.py in backend
and alldetails in frontend

if User download a video then once download complete it should set or save (db) true in `isDownloadComplele` and set or save (db ) path in `filesave`

if `isDownloadComplele` is `True` then show icon with python function in frontend
else dont show it

**Comment by amantiwari1** [comment]
it is added new feature for now so i am going to close it
