### ISSUE TITLE
Use the text area to add one url by time

### ISSUE THREAD

**Issue by raulpy271** [amantiwari1/youtube-GUI#11]
I guess that idea to have a single text area to paste different url's is bad.

Because every time that the user pastes a new url the app will have to handle old and news urls. It will have to decide which url is new or not. These increase the processing and complexity of the application. Besides, the app has to handle any change, for example, if the user adds space or a new line the app will process all links already processed.

To solve it I propose the following: Create an 'Add' button before the download button. So the app will handle a link only when the user clicks on it. Besides, the text area will have only a link by time. 

These will work this way: The user inserts a link and clicks on the add button, if the link is correct the app will show the video/playlist card and clear the text area. After it, the user can insert a new link or download these inserted.

With these changes, the app will process less because it won't process links already processed. Besides she won't care about useless changes (as space added), it will only when the user clicks on the 'Add' button.

@amantiwari1, what do you think about it?

**Comment by amantiwari1** [comment]
Great Idea!! i will work on it!!

**Comment by amantiwari1** [comment]
done i have added add btn check out - https://github.com/amantiwari1/youtube-GUI/commit/48ce0f7ccffe4e7128970f2f889b3716c6b90695

**Comment by amantiwari1** [comment]
https://github.com/raulpy271/youtube-GUI/pull/2
