### ISSUE TITLE
downloading process is still here in frontend while backend said already download 

### ISSUE THREAD

**Issue by amantiwari1** [amantiwari1/youtube-GUI#15]
we need to change bad code to good code in download function 

first we need to understand this function

try download 10 mb video, you will find downloading is still here  in frontend while backend said already done download 

I dont know where is issue in download function? i copied that function from  stackoverflow😂

let me know  did you find issue once download 10 mb!!
@raulpy271

**Comment by raulpy271** [comment]
Hey man, I'm studying about the requests library. Here's the [docs](https://2.python-requests.org/en/master/user/quickstart/), It explains the code that you copied. 

I tested in my machine and the connection is working, the app streams the video and saves it. So I guess that the problem should be when calculating the percentage, or when choosing the chuck_size, I don't know why the value is 4096 bytes.

Maybe tomorrow I try to understand what is the problem, exactly.

**Comment by raulpy271** [comment]
I'm rewriting the download function and it is working, the percentage is correct.  I didn't update my code, because of the error in the other issue. But have you any updates on this function? It will send the percentage to the user yet? Did you fixed it?

**Comment by amantiwari1** [comment]
no! I didn't fix download function 
I changed code in only typescript

**Comment by amantiwari1** [comment]
go ahead fix it

**Comment by amantiwari1** [comment]
did you fix it? @raulpy271

**Comment by raulpy271** [comment]
Not yet. I'm watching some lessons now. Did you want to fix it?

**Comment by amantiwari1** [comment]
no, i am building something frontend
