### ISSUE TITLE
Show error when the link is correct

### ISSUE THREAD

**Issue by raulpy271** [amantiwari1/youtube-GUI#16]
If the user inserts a valid link to a single video the app shows the card of the video, but also shows the message: 'Please enter a valid YouTube URL'.

Root of the error: Before the commit 356ffbcfc5e134e51f000fffa4ebefde6eaa060d the state of the cards is changed in the frontend (for the functions `oneVideo` and `onePlaylist`). After the above commit, the functions `Add_Details` and `Get_Data_Details_Playlists` also change the state. So, the frontend functions expects that the backend returns some data, which not happens, so the frontend concludes that the link is invalid.

Also, this error is from a bed conceptual idea: the backend doesn't should change the state of the interface, this is a role for the frontend. The MVC(and whatever similar pattern), divide the application into layers to turn easy to understand and to turn clear the role of each layer. If the backend could change the state of the interface then it's breaking the principles of a layered system, because the backend should change the database and the frontend should change the state of the front, not the other way around.

So my solution is the following: the function `Add_Details` and `Get_Data_Details_Playlists` should return the data of the videos while the function `oneVideo` and `onePlaylist` should set the state.

@amantiwari1, what do you think? I'm not a master in MVC, actually, I didn't read much about it, so feels free to fix me in some points.

**Comment by amantiwari1** [comment]
actually I didn't fix it that's why it show error because I was focus on database Well I am going to fix it quickly
if user inserts a valid link then it should return `true` and else `false` if something wrong

I am working on it now  

it is working backend and frontend in change in both side 

`the backend should change the database and the frontend should change the state of the front`

could you tell example for above? 
@raulpy271

**Comment by amantiwari1** [comment]
> So my solution is the following: the function Add_Details and Get_Data_Details_Playlists should return the data of the videos while the function oneVideo and onePlaylist should set the state.

it would increase code so we dont need it because i fixed it and remove set in input.tsx today

**Comment by raulpy271** [comment]
> it is working backend and frontend in change in both side
> could you tell the example for above?

Imagine that we have a bug in the interface, the question that comes to mind is where this bug come from?  In a well-designed layered system we known that the bug comes from some error in the frontend. But, In a system where all layers can change all layers the bug can come from anywhere because everyone can change the interface.

**Comment by raulpy271** [comment]
> it would increase code so we dont need it because i fixed it and remove set in input.tsx today

I don't agree with you. Decisions shouldn't be made only by seeing the code length. For me, more code doesn't always imply more complex software. I this case we are giving a bit more code, but we are winning a system more decoupled, which is a good trade for me.

**Comment by raulpy271** [comment]
Maybe, this conversation is bike-shedding in a small system like this. But, I like to think that it's a large system, it's only my philosophy. You can leave the code like is.

**Comment by amantiwari1** [comment]
okay you are right!! change it you know sorry for remove some code you can change back to code

**Comment by raulpy271** [comment]
Don't worry man, you can be right. But I will change it.

**Comment by amantiwari1** [comment]
`Show error when the link is correct` is already fixed so i am going to close it
