### ISSUE TITLE
Doing useless database query

### ISSUE THREAD

**Issue by raulpy271** [amantiwari1/youtube-GUI#17]
Why every time that the user adds a new video link the backend add the new video in the db and then queries all video and set all video in the interface? 

Is most useful to query only the new video and then add it using  `DetailsReducer` with the action `add`. With this method, we save some queries in the db. 

@amantiwari1, what is your opinion?

**Comment by amantiwari1** [comment]
yes I know I didn't write better code😅

**Comment by raulpy271** [comment]
No problem, I will do some refactoring

**Comment by amantiwari1** [comment]
just remove `eel.set_AllDetails(Get_All_Details())` and add return `{ one vidoe details }` in main.py

and input.tsx add code in `detailsreducer` 

that's it
