### ISSUE TITLE
Error when stating the database

### ISSUE THREAD

**Issue by raulpy271** [amantiwari1/youtube-GUI#18]
I merged in my local branch the code from the main branch, And when I try to run the app, It raises the following error:

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: video.savefile
[SQL: SELECT video.id AS video_id, video.url AS video_url, video.title AS video_title, video.thumbnail AS video_thumbnail, video."downloadPercent" AS "video_downloadPercent", video.videoquality AS video_videoquality, video.savefile AS video_savefile 
FROM video]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
```

I didn't try to solve it, @amantiwari1 did you have any idea?

**Comment by amantiwari1** [comment]
delete `data.sqlite3` file first then it is working 
and please update code because I just changed just now

Glad, you are back 
@raulpy271

**Comment by amantiwari1** [comment]
resolved the issue? @raulpy271

**Comment by raulpy271** [comment]
Yeah man, I deleted and it works
