### ISSUE TITLE
Error when calling ffmpeg

### ISSUE THREAD

**Issue by raulpy271** [amantiwari1/youtube-GUI#3]
To call ffmpeg, the code [`downloadvideo.py`](https://github.com/amantiwari1/youtube-GUI/blob/main/backend/downloadvideo.py) use the method `call` of the lib subprocess. See an example:

```python
subprocess.call(f'ffmpeg.exe -y -i "{vidname}" -i "{audname}" -c:v copy -c:a aac "{outname}"', shell=True)
```

In my machine, this raises an error because the command should be passed in a list, like this:

```python
subprocess.call(['ffmpeg', '-i', 'input.avi', 'output.mp4'])
```

@amantiwari1, what do you think?

**Comment by amantiwari1** [comment]
It is good!! @raulpy271

**Comment by raulpy271** [comment]
Nice, It throws an error to you too?

**Comment by amantiwari1** [comment]
No it works at any platform @raulpy271

**Comment by amantiwari1** [comment]
Try it 

https://github.com/kkroening/ffmpeg-python/issues/506

Let me know if it works and fast than ffmpeg command

**Comment by amantiwari1** [comment]
> Nice, It throws an error to you too?
> 
> Edit: It's not an error because the usage of `ffmpeg.exe`. In my machine, I changed the command to:
> 
> ```python
> subprocess.call(f'ffmpeg -y -i "{vidname}" -i "{audname}" -c:v copy -c:a aac "{outname}"', shell=True)
> ```
> But it fails in the same way.

Did you delete ffmpeg.exe in your repo?

**Comment by raulpy271** [comment]
I don't know if using the `ffmpeg-python` library will work for you. Because when the library will convert the python commands to the shell command will look like: `ffmpeg <args>`, but you need that it been `ffmpeg.exe <args>`, right?

**Comment by raulpy271** [comment]
I don't deleted it, but the binary is compiled to windows

**Comment by raulpy271** [comment]
> No, It works at any platform!! @raulpy271

I don't understand how it's works, because the command passed to `.call` should be in list format, see the [docs](https://docs.python.org/3/library/subprocess.html#subprocess.run) of the module. Besides, for me, it works only when I pass the command in list format.

**Comment by amantiwari1** [comment]
No, it works for me

**Comment by amantiwari1** [comment]
Make sure remove `subprocess` call and add code in `ffmpeg-python` which I sent you link above 
I think it might be resolved issue
