### ISSUE TITLE
Valid Youtube Url and Playlist Url

### ISSUE THREAD

**Issue by amantiwari1** [amantiwari1/youtube-GUI#5]
there are 3 main url in youtube  

url 1 : https://www.youtube.com/watch?v=........... (`11 char`)  - `one video`

url 2 : https://www.youtube.com/watch?v=........... &list=.............................(`11 char in watch and 34 char in list`) - `Playlist`

url 3 : https://www.youtube.com/playlist?list=................................ (`34 char in playlist`) -`Playlist`

If url is same as url 1  then it should true and run function ( one video funtion )

else if url is same as url 2 or url 3 then it should true and run function ( multiple video function )

otherwise it will popup wrong link

I am able to figure out how to do it by using regex here is code below:

https://github.com/amantiwari1/youtube-GUI/blob/8fb1983c7387fe1553a4b5d96eee8eb22b92ec1b/src/components/Input.tsx#L74-L140

But Main issue 
if more than 11 char then it return true which is wrong that mean regex is wrong ,
and cant figure out how to use url 2 in regex

can you help me for this? @raulpy271

**Comment by raulpy271** [comment]
Hi @amantiwari1, About the regex to match with URL 1:

Here's the regex the you use:

```javascript
var oneVideoUrl = new RegExp(`https:\/\/www\.youtube\.com\/watch?.*=...........`); 
```
This regex seems wrong in some points, but one of them is that when you use `url.match(oneVideoUrl)` this will search for a match in any substring of `url` instead search for the exact match. To match the entire string you should use the chars `^$`.

Try this version:

```javascript
oneVideoUrl = /^https:\/\/www\.youtube\.com\/watch\?v=\S{11}\s*$/
```

Use it to return true if it matches or false otherwise:

```javascript
oneVideoUrl.test(url)
```

**Comment by raulpy271** [comment]
I will try to write patterns to the others url's

**Comment by amantiwari1** [comment]
@raulpy271  Great work! how did you find that? I tired it to find solution but had no luck 


if someone enter correct url along with one or more space in the end line like `https://www.youtube.com/watch?v=........... (space)` . 
The result is return false so we should think how to this url should remove space in the end line!

**Comment by raulpy271** [comment]
Here's the regexs to match to playlist:

```javascript
playlistUrl = /^https:\/\/www\.youtube\.com\/playlist\?list=\S{34}\s*$/
playlistUrlWithTheFirstVideoSpecified = /^https:\/\/www\.youtube\.com\/watch\?v=\S{11}&list=\S{34}\s*$/
```

@amantiwari1, please check if they are correct

**Comment by raulpy271** [comment]
> if someone enter correct url along with one or more space in the end line like `https://www.youtube.com/watch?v=........... (space)` .
> The result is return false so we should think how to this url should remove space in the end line!

I considered it, so I added `\s*$` to match with URLs that can have spaces in the end. Even with spaces in the end they result true for me.

**Comment by amantiwari1** [comment]
Really cool !! @raulpy271 
all url regex is working including space
so are you going to fix it or me?

**Comment by raulpy271** [comment]
> so are you going to fix it or me?

Whatever, but if you want I can fix it and send a pull request.

**Comment by amantiwari1** [comment]
> Whatever, but if you want I can fix it and send a pull request.

Go fix it!! @raulpy271
