### ISSUE TITLE
Error when inserting a valid url

### ISSUE THREAD

**Issue by raulpy271** [amantiwari1/youtube-GUI#6]
@amantiwari1,

I changed the regex's of issue #5, but when I insert a valid URL I'm getting the following error:

```
TypeError: can't convert undefined to object

  111 | 
  112 | console.log(message)
  113 | if (message !== true) {
> 114 |     SetAllDetail({ message, type: 'add' });
      | ^
  115 | }
  116 | setCardLoading(false)
  117 | 
```

I printed the value of `message` and it is null. Even before the changes that I did today the error already exist.

**Comment by amantiwari1** [comment]
@raulpy271  did you updated code? I fixed it

**Comment by raulpy271** [comment]
You are right, I haven't updated the last commit
